logger:
  level: "debug"
  development: true

mongo:
  host: "mongo"
  database: "tenant"
  replica-set: rs0

security:
  jwks:
    jwks-url: "http://logto:3001/oidc/jwks"
    audience: "https://api.sokolshop.com"
  client-credentials:
    client-id: "tenant-service-m2m"
    token-url: "http://logto:3001/oidc/token"

kafka:
  brokers: "redpanda:29092"
  schema-registry:
    url: "http://redpanda:8081"
    auto-register-schemas: true

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false

pprof:
  enabled: true
  port: 6060
