logger:
  level: "debug"
  development: true

mongo:
  host: "localhost"
  database: "tenant"
  direct-connection: true

kafka:
  brokers: "localhost:9092"
  schema-registry:
    url: "http://localhost:8084"
    auto-register-schemas: true

security:
  token:
    jwks-url: "http://localhost:8080/oauth/v2/keys"

observability:
  otel-collector-endpoint: ""
  tracing:
    enabled: true
  metrics:
    enabled: false