logger:
  level: "debug"
  development: true

mongo:
  host: "mongo"
  database: "tenant"
  replica-set: rs0

security:
  token:
    jwks-url: "http://zitadel-api:8080/oauth/v2/keys"
    host-override: "localhost"

kafka:
  brokers: "redpanda:29092"
  schema-registry:
    url: "http://redpanda:8081"
    auto-register-schemas: true

observability:
  otel-collector-endpoint: "otel-collector-opentelemetry-collector.observability.svc:4317"
  tracing:
    enabled: true
  metrics:
    enabled: false

pprof:
  enabled: true
  port: 6060
