logger:
  level: "debug"
  development: true

mongo:
  host: "localhost"
  database: "tenant"
  direct-connection: true

kafka:
  brokers: "localhost:9092"

security:
  jwks:
    jwks-url: "http://localhost:3001/oidc/jwks"
    audience: "https://api.sokolshop.com"
  client-credentials:
    client-id: "tenant-service-m2m"
    token-url: "http://localhost:3001/oidc/token"

observability:
  otel-collector-endpoint: ""
  tracing:
    enabled: true
  metrics:
    enabled: false